#!/usr/bin/env bash
# Build the SIGIR version (paper/sigir/main.tex, acmart sigconf, anonymous review).
#   bash scripts/sigir_build.sh
# Writes paper/sigir/refs.bib from reports/citations_verified.bib without the note fields (they are
# verification records, not reference text), draws the single-column figures of paper/sigir/
# (scripts/figures.py --sigir), builds in a scratch copy and leaves the PDF in build/sigir/. Then
# scripts/sigir_check.py reads the build: the body has to end on page 9. The build runs with TZ=UTC,
# so the PDF's timestamps carry no local time zone (the submission is anonymous). Needs texlive-publishers
# (acmart), texlive-fonts-extra (Libertine, Inconsolata, newtx) and texlive-plain-generic.
set -euo pipefail
repo=$(cd "$(dirname "$0")/.." && pwd)
python3 - "$repo/reports/citations_verified.bib" "$repo/paper/sigir/refs.bib" <<'PY'
import re, sys
src = open(sys.argv[1]).read()
out, i = [], 0
for m in re.finditer(r'(?im)^\s*note\s*=\s*\{', src):
    j = m.end(); depth = 1
    while depth:
        depth += {'{': 1, '}': -1}.get(src[j], 0); j += 1
    while j < len(src) and src[j] in ' ,': j += 1
    if j < len(src) and src[j] == '\n': j += 1
    out.append(src[i:m.start()]); i = j
out.append(src[i:])
txt = ''.join(out)
assert not re.search(r'(?im)^\s*note\s*=', txt)
open(sys.argv[2], 'w').write("% generated by scripts/sigir_build.sh from reports/citations_verified.bib (note fields removed)\n" + txt)
PY
python3 "$repo/scripts/figures.py" --sigir > /dev/null
work=$(mktemp -d); trap 'rm -rf "$work"' EXIT
mkdir -p "$work/paper"
cp -r "$repo/paper/sigir" "$repo/paper/figures" "$work/paper/"
(cd "$work/paper/sigir" && TZ=UTC latexmk -pdf -bibtex -interaction=nonstopmode main.tex > build.log 2>&1) || { tail -40 "$work/paper/sigir/main.log"; exit 1; }
mkdir -p "$repo/build/sigir"
cp "$work/paper/sigir/main.pdf" "$repo/build/sigir/dirvec_sigir_review.pdf"
cp "$work/paper/sigir/main.log" "$repo/build/sigir/main.log"
grep -E "^(!|LaTeX Warning|Package natbib Warning)|undefined" "$work/paper/sigir/main.log" | sort | uniq -c | head -20 || true
echo "pages: $(pdfinfo "$repo/build/sigir/dirvec_sigir_review.pdf" | awk '/^Pages/{print $2}')"
python3 "$repo/scripts/sigir_check.py" "$repo"/results/*.md "$repo/BRIEF.md" --pdf "$repo/build/sigir/dirvec_sigir_review.pdf"
